/** Single source of truth for URLs. Never hard-code a path in a component. */
export const routePaths = {
  root: '/',
  registration: '/registration',
  customerType: '/customer-type',
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    otp: '/auth/otp',
    passcode: '/auth/passcode',
    createProfile: '/auth/create-profile',
    customerType: '/auth/customer-type',
  },
  dashboard: '/dashboard',
  gst: {
    root: '/gst',
    registration: '/gst/registration',
    returns: '/gst/returns',
    filing: '/gst/filing',
    filePeriod: '/gst/file-period',
    fileUpload: '/gst/file-upload',
    fileReview: '/gst/file-review',
    filePayment: '/gst/file-payment',
    fileSuccess: '/gst/file-success',
    fileReceipt: '/gst/file-receipt',
    amendment: '/gst/amendment',
    compliance: '/gst/compliance',
    complianceSubmitted: '/gst/compliance/submitted',
    cancellation: '/gst/cancellation',
    cancellationSubmitted: '/gst/cancellation/submitted',
    certificate: '/gst/certificate',
    detail: (id = ':id') => `/gst/${id}`,
    track: (id = ':id') => `/gst/${id}/track`,
  },
  itr: {
    root: '/itr',
    fileItr: '/itr/file-itr',
    trackMyReturn: '/itr/track-my-return',
    itrFiling: '/itr/itr-filing',
    tdsRefund: '/itr/tds-refund',
    previousYearItr: '/itr/previous-year-itr',
    revisedItr: '/itr/revised-itr',
    taxNoticeAssistance: '/itr/tax-notice-assistance',
    tdsRefundEstimator: '/itr/tds-refund-estimator',
    taxComputation: '/itr/tax-computation',
  },
  loans: '/loans',
  loansHomeLoan: '/loans/home-loan',
  loansPersonalLoan: '/loans/personal-loan',
  loansBusinessLoan: '/loans/business-loan',
  loansPropertyLoan: '/loans/property-loan',
  loansVehicleLoan: '/loans/vehicle-loan',
  loansWorkingCapitalLoan: '/loans/working-capital-loan',
  loansMachineryLoan: '/loans/machinery-loan',
  loansProjectFinance: '/loans/project-finance',
  loansMsmeLoan: '/loans/msme-loan',
  loansStatus: (id = ':id') => `/loans/status/${id}`,
  insurance: '/insurance',
  incorporation: {
    root: '/incorporation',
    selectType: '/incorporation/select-type',
    companyDetails: '/incorporation/company-details',
    registeredOffice: '/incorporation/registered-office',
    promoterDetails: '/incorporation/promoter-details',
    capitalDetails: '/incorporation/capital-details',
    documentsKyc: '/incorporation/documents-kyc',
    linkedRegistrations: '/incorporation/linked-registrations',
    reviewApplication: '/incorporation/review-application',
    feesPayment: '/incorporation/fees-payment',
    submissionSuccess: '/incorporation/submission-success',
    applicationTracking: '/incorporation/application-tracking',
    receipt: '/incorporation/receipt',
  },
  business: {
    root: '/business',
  },
  payments: '/payments',
  paymentReceipt: (id = ':id') => `/payments/receipt/${id}`,
  paymentReceiptDirect: '/payments/receipt',
  documents: '/documents',
  applications: '/applications',
  services: '/services',
  allServices: '/all-services',
  profile: '/profile',
  profilePersonal: '/profile/personal',
  profileKyc: '/profile/kyc',
  support: '/support',
  legal: {
    terms: '/legal/terms',
    privacy: '/legal/privacy',
    document: (id = ':documentId') => `/legal/${id}`,
  },
  notifications: '/notifications',
  notFound: '*',
} as const
